// STEP-2 DESIGN THE TYPES OF ACTIONS THE STATE MIGHT SUFFER
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const SUBMIT_TODO = "SUBMIT_TODO";
export const TOGGLE_TODO_COMPLETE = "TOGGLE_TODO_COMPLETE";
export const REMOVE_TODO = "REMOVE_TODO";
export const CLEAR_COMPLETE = "CLEAR_COMPLETE";